version: "3.3"

services:
    server: 
        build: ./
        ports: 
            - 8000:8080
        depends_on: 
            - postgresdb
    
    postgresdb:
        image: postgres:latest
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 123456
        ports:
            - 5434:5434